In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv('train_labels.csv')[['ID', ' Detection']]


* 根据ID查询全部相关的bbox
* 将Detection转换为数值
* 存储到数组中
* 坐标变换
data = [:, x1, y1, x2, y2]
box = 

In [70]:
def compute_hw(detection):
    loc = [int(x) for x in detection.split(' ')]
    x1, y1, x2, y2 = loc
    h = y2 - y1
    w = x2 - x1
    return h, w

In [21]:
def compute_area(detection):
    loc = [int(x) for x in detection.split(' ')]
    x1, y1, x2, y2 = loc
    h = y2 - y1
    w = x2 - x1
    area = (y2 - y1) * (x2 - x1)
    return area if area > 0 else None
def compute_ratio(detection):
    loc = [int(x) for x in detection.split(' ')]
    x1, y1, x2, y2 = loc
    h = y2 - y1
    w = x2 - x1
    return h / w
def hw(detection):
    loc = [int(x) for x in detection.split(' ')]
    x1, y1, x2, y2 = loc
    h = y2 - y1
    w = x2 - x1
    return h, w
#     return h/w if (h>0 and w>0) else None
def get_loc_value(detection):
    return [int(x) for x in detection.split(' ')]

In [25]:
df.apply(lambda x:get_loc_value(x[' Detection']), axis=1).d

0           [311, 707, 472, 842]
1           [351, 631, 452, 721]
2           [438, 473, 519, 563]
3           [420, 553, 557, 688]
4           [501, 446, 641, 607]
5           [602, 370, 759, 548]
6           [809, 436, 953, 603]
7           [709, 568, 862, 721]
8           [560, 609, 719, 781]
9           [506, 733, 643, 884]
10          [430, 845, 577, 978]
11          [686, 713, 848, 853]
12         [564, 888, 715, 1041]
13         [393, 969, 546, 1120]
14        [610, 1015, 736, 1159]
15        [465, 1149, 606, 1287]
16        [612, 1217, 744, 1345]
17        [709, 1321, 858, 1461]
18        [798, 1422, 939, 1542]
19        [829, 1542, 907, 1674]
20       [877, 1533, 1017, 1663]
21       [916, 1673, 1015, 1795]
22       [956, 1620, 1097, 1766]
23       [959, 1401, 1078, 1530]
24       [967, 1278, 1102, 1412]
25        [756, 1095, 902, 1229]
26       [906, 1116, 1048, 1251]
27         [728, 912, 864, 1049]
28         [849, 987, 987, 1129]
29          [849, 809, 982, 943]
          

In [5]:
df['area'] = df.apply(lambda x:compute_area(x[' Detection']), axis=1)
df['hw_ratio'] = df.apply(lambda x:compute_ratio(x[' Detection']), axis=1)
df['hw'] = df.apply(lambda x:hw(x[' Detection']), axis=1)

In [7]:
df.describe()

area      hw_ratio
count  30942.000000  30942.000000
mean   16488.169155      0.995808
std    10564.601825      0.142844
min      150.000000      0.460870
25%     8277.000000      0.904255
50%    14256.000000      0.986842
75%    21158.000000      1.076251
max    82654.000000      4.166667

In [9]:
agg_count = df.groupby('ID')['area'].count()
# agg_count.plot()

In [18]:
agg_ = df.groupby('ID')
agg_.get_group('0009496A.jpg').

ID            Detection   area  hw_ratio          hw
115  0009496A.jpg      407 671 526 771  11900  0.840336  (100, 119)
116  0009496A.jpg      378 757 502 855  12152  0.790323   (98, 124)
117  0009496A.jpg      521 712 639 812  11800  0.847458  (100, 118)
118  0009496A.jpg      574 593 702 719  16128  0.984375  (126, 128)
119  0009496A.jpg      691 549 814 658  13407  0.886179  (109, 123)
120  0009496A.jpg      478 862 600 961  12078  0.811475   (99, 122)
121  0009496A.jpg     424 961 538 1050  10146  0.780702   (89, 114)
122  0009496A.jpg    331 1115 445 1206  10374  0.798246   (91, 114)
123  0009496A.jpg    476 1155 589 1232   8701  0.681416   (77, 113)
124  0009496A.jpg    513 1304 629 1385   9396  0.698276   (81, 116)
125  0009496A.jpg    506 1369 616 1457   9680  0.800000   (88, 110)
126  0009496A.jpg    600 1355 707 1453  10486  0.915888   (98, 107)
127  0009496A.jpg    609 1486 708 1568   8118  0.828283    (82, 99)
128  0009496A.jpg    584 1690 696 1769   8848  0.705357   (79, 112)
129  0009496A.jpg    701 1597 794 1678   7533  0.870968    (81, 93)
130  0009496A.jpg    782 1718 894 1791   8176  0.651786   (73, 112)
131  0009496A.jpg    895 1635 989 1715   7520  0.851064    (80, 94)
132  0009496A.jpg    701 1484 788 1562   6786  0.896552    (78, 87)
133  0009496A.jpg    814 1495 914 1574   7900  0.790000   (79, 100)
134  0009496A.jpg    746 1395 848 1465   7140  0.686275   (70, 102)
135  0009496A.jpg   910 1466 1000 1550   7560  0.933333    (84, 90)
136  0009496A.jpg    708 1309 811 1387   8034  0.757282   (78, 103)
137  0009496A.jpg    655 1242 769 1321   9006  0.692982   (79, 114)
138  0009496A.jpg    608 1175 726 1265  10620  0.762712   (90, 118)
139  0009496A.jpg    653 1141 766 1221   9040  0.707965   (80, 113)
140  0009496A.jpg    735 1164 821 1254   7740  1.046512    (90, 86)
141  0009496A.jpg    772 1256 878 1354  10388  0.924528   (98, 106)
142  0009496A.jpg    800 1200 910 1286   9460  0.781818   (86, 110)
143  0009496A.jpg    856 1299 963 1375   8132  0.710280   (76, 107)
144  0009496A.jpg    858 1350 952 1419   6486  0.734043    (69, 94)
..            ...                  ...    ...       ...         ...
261  0009496A.jpg    1517 803 1623 895   9752  0.867925   (92, 106)
262  0009496A.jpg    1587 774 1676 866   8188  1.033708    (92, 89)
263  0009496A.jpg   1543 924 1654 1009   9435  0.765766   (85, 111)
264  0009496A.jpg   1593 965 1682 1032   5963  0.752809    (67, 89)
265  0009496A.jpg   1645 908 1744 1000   9108  0.929293    (92, 99)
266  0009496A.jpg   1640 987 1722 1061   6068  0.902439    (74, 82)
267  0009496A.jpg  1670 1074 1767 1170   9312  0.989691    (96, 97)
268  0009496A.jpg  1777 1162 1874 1237   7275  0.773196    (75, 97)
269  0009496A.jpg  1758 1077 1867 1163   9374  0.788991   (86, 109)
270  0009496A.jpg  1858 1130 1954 1211   7776  0.843750    (81, 96)
271  0009496A.jpg  1967 1116 2059 1206   8280  0.978261    (90, 92)
272  0009496A.jpg   1716 958 1822 1045   9222  0.820755   (87, 106)
273  0009496A.jpg  1854 1013 1947 1104   8463  0.978495    (91, 93)
274  0009496A.jpg   1866 950 1970 1028   8112  0.750000   (78, 104)
275  0009496A.jpg   1958 954 2043 1053   8415  1.164706    (99, 85)
276  0009496A.jpg    1795 886 1896 984   9898  0.970297   (98, 101)
277  0009496A.jpg    1733 822 1833 917   9500  0.950000   (95, 100)
278  0009496A.jpg    1891 864 1995 970  11024  1.019231  (106, 104)
279  0009496A.jpg    1822 779 1936 880  11514  0.885965  (101, 114)
280  0009496A.jpg    1960 866 2030 955   6230  1.271429    (89, 70)
281  0009496A.jpg    1949 758 2043 829   6674  0.755319    (71, 94)
282  0009496A.jpg    1947 696 2056 785   9701  0.816514   (89, 109)
283  0009496A.jpg    1670 696 1772 793   9894  0.950980   (97, 102)
284  0009496A.jpg    1765 716 1853 820   9152  1.181818   (104, 88)
285  0009496A.jpg    1816 655 1914 770  11270  1.173469   (115, 98)
286  0009496A.jpg    1890 652 1965 744   6900  1.226667    (92, 75)
287  0009496A.jpg    2008 626 2122 736  12540  0.964912  (110, 114)
288

In [52]:
agg_count.describe()

count    250.000000
mean     123.768000
std       60.392975
min       44.000000
25%       80.000000
50%      111.000000
75%      144.500000
max      273.000000
Name: area, dtype: float64

In [80]:
agg_area = df.groupby('ID').mean()
agg_area

area  hw_ratio
ID                                  
0009496A.jpg   9597.522727  0.897214
000C7C0E.jpg  24206.093750  0.996884
01D4FEFB.jpg   7193.513966  1.007572
02B90DB7.jpg  12294.771930  0.897901
02EDEB01.jpg  12050.414966  0.937490
038D7000.jpg  24335.175000  0.993694
03CF22F1.jpg  53765.250000  0.988542
046F4967.jpg  19407.819820  1.025887
0492570A.jpg   8000.647799  0.915767
04BD494B.jpg  15083.147887  1.007339
0631BF82.jpg  23327.772727  1.057556
07DD5503.jpg  17082.570248  0.974660
08923C9F.jpg  13943.410072  1.032249
08F7E2BB.jpg  26069.575472  1.020872
09B27635.jpg  17123.875776  1.007192
0B4F3CC3.jpg  26364.283951  0.958358
0BFB817C.jpg  10054.497238  1.017282
0C7CB7B9.jpg  18046.798165  0.913129
0E8C93E4.jpg  45224.435484  0.991656
0EAC74AF.jpg   5511.861004  0.941306
0EDF9500.jpg   7027.861423  0.992513
0EED02C3.jpg  27325.903226  0.964754
1099EFCE.jpg  33072.900000  1.029705
13641B22.jpg  20466.268966  1.008632
147DAD30.jpg   7620.234201  1.007772
1594D4CC.jpg  21333.890909  0.968636
162EF44D.jpg  18414.912621  1.038395
1688B30E.jpg  19731.072289  0.795450
18C1A02C.jpg  17156.234783  0.965312
1B82FF85.jpg   6112.153558  1.006738
...                    ...       ...
E05ABCF0.jpg  15376.094340  1.095808
E42F504E.jpg  23934.072072  1.023801
E46D744F.jpg  25804.462500  1.009256
E636D4C4.jpg   7511.915179  0.950145
E646C7E9.jpg  16463.566038  0.929671
E6D7C4C8.jpg  20142.842593  0.994676
E802A308.jpg  16799.595041  0.970891
E8A7BB7D.jpg  22833.607843  0.935303
EAAB35B1.jpg  32940.067797  0.921143
EAC26CCD.jpg  16235.649635  1.035665
EB8ECF1A.jpg  33278.046154  0.970211
ED64EFB9.jpg  40953.355556  0.976487
EDB2FA69.jpg   6919.145522  1.011076
EFE77AB2.jpg  22580.445378  0.970474
F0779891.jpg   8949.927778  1.004005
F1477D62.jpg  16784.309091  0.957387
F2011360.jpg  13635.235294  0.869956
F2179DD4.jpg  35834.090909  1.055052
F4CDD578.jpg   5752.513966  0.995756
F5129F56.jpg  45963.919355  0.943907
F5164D4F.jpg  10693.038168  0.995253
F5501E38.jpg  18619.639175  0.983094
F6309AF1.jpg   4694.607407  1.002699
F6E0119D.jpg  10425.162921  0.948961
F766C97D.jpg  20570.487805  0.944384
F8656E74.jpg   5821.189189  1.064583
F8C0AD90.jpg  27854.306452  0.960625
FAC06BA2.jpg  17979.976000  0.972455
FCE7645C.jpg  46075.033898  0.982344
FE4C5D3F.jpg  38655.903226  0.978324

[250 rows x 2 columns]

In [56]:
agg_area.describe()

area
count    250.000000
mean   20966.370485
std    11612.664004
min     4694.607407
25%    12954.078968
50%    19124.973913
75%    26323.319213
max    64384.155556

In [57]:
agg_area.loc[agg['area'] > agg.describe().loc['75%'].data]

/home/wdd/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Series.data is deprecated and will be removed in a future version
  """Entry point for launching an IPython kernel.


area
ID                        
03CF22F1.jpg  53765.250000
0B4F3CC3.jpg  26364.283951
0E8C93E4.jpg  45224.435484
0EED02C3.jpg  27325.903226
1099EFCE.jpg  33072.900000
2798F642.jpg  39603.500000
36A7E5D4.jpg  29560.901639
3ABBD9FD.jpg  38237.322581
3D218F21.jpg  28194.551282
3F343E06.jpg  37254.919355
452A534A.jpg  34955.967742
469EB470.jpg  35910.564516
4718DA7F.jpg  39893.644444
4CF58401.jpg  35799.885246
52575287.jpg  58559.488889
554F4CE0.jpg  47920.577778
574E9C80.jpg  28183.026316
5A7370CF.jpg  28526.201923
5BCDAEB8.jpg  31391.419355
638FA776.jpg  47925.580645
6B91D242.jpg  35055.419355
6F76366B.jpg  34377.983871
7421D3CD.jpg  32530.508197
7E0BEC70.jpg  31310.986301
8128955A.jpg  35947.677419
881B376F.jpg  57954.511111
8A057EB9.jpg  35932.080645
8BD7A993.jpg  40520.920635
8D9FAC03.jpg  41029.539683
8EF392EA.jpg  31344.289157
...                    ...
9D46BC0C.jpg  27604.580247
9EA71EB4.jpg  29124.552239
9F1740D8.jpg  33199.682927
A2A2E11D.jpg  64384.155556
A3EEA8A1.jpg  26734.521277
A47F943C.jpg  51865.777778
A6EE237B.jpg  26614.647727
A6F01C78.jpg  30663.861538
A8658634.jpg  26906.870968
AFD1AE2E.jpg  40643.111111
B905D0AB.jpg  37936.258065
BA9F0F0D.jpg  33292.854839
BB32A6B9.jpg  41165.770492
BB917D5A.jpg  28148.658228
BF5A2B05.jpg  26439.377193
C3FCD4A6.jpg  35997.483871
C911FE0A.jpg  37671.258065
C99C4D23.jpg  38646.575758
CC61344D.jpg  62794.155556
CCB5DBEF.jpg  26643.087500
D2B83E2C.jpg  36382.548387
D4C4E4DB.jpg  31997.774194
EAAB35B1.jpg  32940.067797
EB8ECF1A.jpg  33278.046154
ED64EFB9.jpg  40953.355556
F2179DD4.jpg  35834.090909
F5129F56.jpg  45963.919355
F8C0AD90.jpg  27854.306452
FCE7645C.jpg  46075.033898
FE4C5D3F.jpg  38655.903226

[63 rows x 1 columns]

In [43]:
agg.loc[agg['area'] < agg.describe().loc['25%'].data]

/home/wdd/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Series.data is deprecated and will be removed in a future version
  """Entry point for launching an IPython kernel.


area
ID                        
0009496A.jpg   9597.522727
01D4FEFB.jpg   7193.513966
02B90DB7.jpg  12294.771930
02EDEB01.jpg  12050.414966
0492570A.jpg   8000.647799
0BFB817C.jpg  10054.497238
0EAC74AF.jpg   5511.861004
0EDF9500.jpg   7027.861423
147DAD30.jpg   7620.234201
1B82FF85.jpg   6112.153558
1E5FB1FF.jpg  10985.231250
2338148B.jpg   8505.881226
256C1DBD.jpg   6704.219331
2723542B.jpg   8477.078947
296A3EA4.jpg   5690.393822
34AEBFA3.jpg   7765.433962
353E85DF.jpg   8097.761111
3794BD4B.jpg   7798.623188
41CF3100.jpg   9368.116022
4463FA64.jpg  10910.847134
4D3BE5D5.jpg   6791.933086
54CE2153.jpg  11442.110092
550E6EB2.jpg  10018.561404
570D8DA2.jpg  11071.925287
5858D941.jpg   6952.857143
5A589275.jpg  11200.664557
5BE19523.jpg   9119.181818
6000BA04.jpg   7686.972376
603CC53F.jpg   9903.988636
60639D0F.jpg  12883.407143
...                    ...
8509E501.jpg   7823.955801
8702EAB5.jpg   8218.444030
8777E599.jpg   6310.323308
88292AF2.jpg  12602.840336
898E0058.jpg   5561.856502
92AB4085.jpg   7390.805243
9F1F4BE9.jpg  10366.713115
ACEA2A10.jpg   8870.234286
AD351F54.jpg  12243.366667
B3DF643D.jpg  10695.794872
B4EEFB95.jpg   9687.194444
B9E60B56.jpg   6538.937729
BB4402AE.jpg   8591.280443
BD968624.jpg   7938.752809
C06245D1.jpg   7960.400000
C2871199.jpg   8107.273408
C378D66B.jpg   8350.367742
C85E0C57.jpg   5637.679389
CE4841E1.jpg   6584.731343
D0D2EED9.jpg   7043.886364
DCCA8144.jpg   7745.636943
DEBA2239.jpg   6955.226415
E636D4C4.jpg   7511.915179
EDB2FA69.jpg   6919.145522
F0779891.jpg   8949.927778
F4CDD578.jpg   5752.513966
F5164D4F.jpg  10693.038168
F6309AF1.jpg   4694.607407
F6E0119D.jpg  10425.162921
F8656E74.jpg   5821.189189

[63 rows x 1 columns]

In [3]:
import imgaug
from imgaug import augmenters as iaa
from PIL import Image
import skimage.io as skio
import os

In [25]:
test_data_dir = '/home/wdd/test_dataset/'
train_data_dir = "/home/wdd/train_dataset"
train_imgs_list = os.listdir(train_data_dir)#list all filename
test_imgs_list = os.listdir(test_data_dir)
img_sample = os.path.join(train_data_dir, imgs_list[0])


NameError: name 'imgs_list' is not defined

In [25]:
for i in train_imgs_list:
    img_path = os.path.join(train_data_dir, i)
    img = skio.imread(img_path)
    if img is not None:
        print(img_path)

/home/wdd/train_dataset/0492570A.jpg
/home/wdd/train_dataset/554F4CE0.jpg
/home/wdd/train_dataset/F4CDD578.jpg
/home/wdd/train_dataset/8E24C2B6.jpg
/home/wdd/train_dataset/E42F504E.jpg
/home/wdd/train_dataset/8654EDAC.jpg
/home/wdd/train_dataset/2FDC9E0E.jpg
/home/wdd/train_dataset/5858D941.jpg
/home/wdd/train_dataset/6B91D242.jpg
/home/wdd/train_dataset/0B4F3CC3.jpg
/home/wdd/train_dataset/B3C96BEB.jpg
/home/wdd/train_dataset/6F76366B.jpg
/home/wdd/train_dataset/41CF3100.jpg
/home/wdd/train_dataset/DFE17F7D.jpg
/home/wdd/train_dataset/B4EEFB95.jpg
/home/wdd/train_dataset/FAC06BA2.jpg
/home/wdd/train_dataset/6B898244.jpg
/home/wdd/train_dataset/EAC26CCD.jpg
/home/wdd/train_dataset/4CF58401.jpg
/home/wdd/train_dataset/95D0521E.jpg
/home/wdd/train_dataset/9CC98D4D.jpg
/home/wdd/train_dataset/7EBD1524.jpg
/home/wdd/train_dataset/52CC0B19.jpg
/home/wdd/train_dataset/C32AC471.jpg
/home/wdd/train_dataset/E05ABCF0.jpg
/home/wdd/train_dataset/67B4B0A2.jpg
/home/wdd/train_dataset/574E9C80.jpg
/

/home/wdd/train_dataset/0EDF9500.jpg
/home/wdd/train_dataset/C911FE0A.jpg
/home/wdd/train_dataset/9F1740D8.jpg
/home/wdd/train_dataset/99E783B2.jpg
/home/wdd/train_dataset/296A3EA4.jpg
/home/wdd/train_dataset/8DE6C059.jpg
/home/wdd/train_dataset/7099AEF0.jpg
/home/wdd/train_dataset/6000BA04.jpg
/home/wdd/train_dataset/BB32A6B9.jpg
/home/wdd/train_dataset/3C398D0A.jpg
/home/wdd/train_dataset/8128955A.jpg
/home/wdd/train_dataset/0E8C93E4.jpg
/home/wdd/train_dataset/5BE19523.jpg
/home/wdd/train_dataset/9D496EBE.jpg
/home/wdd/train_dataset/926A4C0C.jpg
/home/wdd/train_dataset/EDB2FA69.jpg
/home/wdd/train_dataset/982B1C73.jpg
/home/wdd/train_dataset/BFC85CA0.jpg
/home/wdd/train_dataset/2A35EC79.jpg
/home/wdd/train_dataset/D8146090.jpg
/home/wdd/train_dataset/4463FA64.jpg
/home/wdd/train_dataset/18C1A02C.jpg
/home/wdd/train_dataset/1EFC66A0.jpg
/home/wdd/train_dataset/408EAD06.jpg
/home/wdd/train_dataset/36A7E5D4.jpg
/home/wdd/train_dataset/E636D4C4.jpg
/home/wdd/train_dataset/57CC2B0B.jpg


In [18]:

seq = iaa.Sequential([
    iaa.OneOf([
        iaa.Fliplr(0.5),
        iaa.Flipud(0.5),
        iaa.PerspectiveTransform(scale=0.125),
        iaa.Affine(rotate=(90))
    ]),
    iaa.OneOf([
        iaa.GaussianBlur(sigma=1.2),#1.2
        iaa.AverageBlur(k=5),#7
        iaa.MedianBlur(k=5)#7
    ]),
    iaa.OneOf([
        iaa.Sharpen(lightness=1.2),#1.1
        iaa.ContrastNormalization((1.5, 1.5)),#1.1,1.2
        iaa.AddToHueAndSaturation((-5,5)),#-5,5
#         iaa.HistogramEqualization()
    ])
])
seq_det = seq.to_deterministic(6)

In [15]:
if not os.path.exists('Gang_enhancedSample'):
    os.makedirs('Gang_enhancedSample')

In [19]:
sample = skio.imread(img_sample)
enhanced_img = seq_det[0].augment_image(sample)
skio.imshow(enhanced_img)

NameError: name 'img_sample' is not defined

In [12]:
iaa.Sharpen(lightness=1.5)(sample)

NameError: name 'sample' is not defined

In [13]:
iaa.HistogramEqualization(F, T)

AttributeError: module 'imgaug.augmenters' has no attribute 'HistogramEqualization'

In [47]:
import torch
import torch.functional as F
import torch.nn as nn

a = torch.randn((1,3,193,193))
c1 = nn.Conv2d(3,10,5)
for i in c1.parameters():
    print('conv2d 5x5x10 para shape:', i.shape)
c2 = nn.Conv2d(10,10,1)
for i in c2.parameters():
    print('conv2d 1x1x10 para shape:', i.shape)
m = nn.MaxPool2d(2)
for i in m.parameters():#每个卷积核只保存一个参数
    print('maxpooling para shape:', i.shape)
bn = nn.BatchNorm2d(10)
for i in bn.parameters():
    print('maxpooling para shape:', i.shape)

no_padding = c1(a)#经过一次5x5x10的Conv2d(no padding)
print('output after conv1:', no_padding.shape)

x = c2(no_padding)#经过一次1x1x10的Conv2d
print('output after conv2:', x.shape)

x = bn(x)
print('output after bn:', x.shape)

x = m(x)#经过一次maxpooling(stride=2)
print('output after maxpoolig:', x.shape)# in // 2

conv2d 5x5x10 para shape: torch.Size([10, 3, 5, 5])
conv2d 5x5x10 para shape: torch.Size([10])
conv2d 1x1x10 para shape: torch.Size([10, 10, 1, 1])
conv2d 1x1x10 para shape: torch.Size([10])
maxpooling para shape: torch.Size([10])
maxpooling para shape: torch.Size([10])
output after conv1: torch.Size([1, 10, 189, 189])
output after conv2: torch.Size([1, 10, 189, 189])
output after bn: torch.Size([1, 10, 189, 189])
output after maxpoolig: torch.Size([1, 10, 94, 94])


### 卷积参数计算
#### 输出feature map尺寸
$$\frac{n-f+p}{s} +1$$
n:输入尺寸 f:卷积核ch存 s:卷积步长 p:padding数量 
>只有卷积核完全覆盖输入计算才有效，但上式算出来的商可能不是整数，惯例是向下取整  

#### 卷积conv2d以及参数量
通常二维图像有多个通道，因此每一张图像实际上的shape是(channel,h,w)，conv2d做的其实是三维卷积，conv2d不仅仅会对二维图像输出后的尺寸变动，更重要的是在通道上的变动，在通道上多样的处理方法也衍生出了很多经典网络

**conv2d权重参数量:**<br>
$$out×in×k×k$$
out:输出通道数量 in:输入通道数量 k:卷积核尺寸
#### 卷积运算计算量
计算conv2d在对输入的feature map卷积的计算量,总体思路是`输出尺寸×卷积的参数量`
$$(\frac{n-f+p}{s}+1)\times out \times in \times k \times k$$
>不考虑求和和bias计算量

### 卷积中padding

1. valid卷积——不使用0填充，卷积核只允许访问图像中能够完全包含整个核的位置，输出的宽度为`n(输入图像尺寸)-f(卷积核的尺寸)+1`(假设stride=1)
在这种情况下，输出的大小每一次都会损失一部分，(一般情况下，影响不大，除非是上百层的网络)
2. same卷积——进行足够的0填充保持每一次输出和输入具有相同大小的尺寸。
$p=(k-1)/2$
p：padding填充数量  k:卷积核的尺寸

In [48]:
import numpy as np

In [54]:
a = np.random.randn(3,3)
print(a >0.5)
print(a)
np.where(a > 0.5)

[[ True False False]
 [ True False False]
 [False False False]]
[[ 0.56594688  0.09129231 -1.70969403]
 [ 0.60264811 -0.11768517  0.21065617]
 [ 0.0687882  -1.05858106 -0.30348314]]


(array([0, 1]), array([0, 0]))