pytorch会自动舍弃图中间的计算结果，所以想要获取这些中间值就要使用hook技术

`register_forward_hook(hook)`
注册module的一个正向传播的hook,


In [1]:
import torch
import numpy as np

from torch.autograd import Variable

In [2]:
x = torch.nn.Sequential()
x.add_module('l1', torch.nn.Linear(1,13))
x.add_module('l2', torch.nn.Linear(13,12))#可以看到使用Sequential()
print(type(x))
y = torch.nn.ModuleList([x for i in range(5)])
for _, i in enumerate(y):
    print('_num:',_, i)#可以看到使用ModuleList支持迭代，支持索引，每个索引为list中相应位置的子模块网络
print(y[1])#支持索引


<class 'torch.nn.modules.container.Sequential'>
_num: 0 Sequential(
  (l1): Linear(in_features=1, out_features=13, bias=True)
  (l2): Linear(in_features=13, out_features=12, bias=True)
)
_num: 1 Sequential(
  (l1): Linear(in_features=1, out_features=13, bias=True)
  (l2): Linear(in_features=13, out_features=12, bias=True)
)
_num: 2 Sequential(
  (l1): Linear(in_features=1, out_features=13, bias=True)
  (l2): Linear(in_features=13, out_features=12, bias=True)
)
_num: 3 Sequential(
  (l1): Linear(in_features=1, out_features=13, bias=True)
  (l2): Linear(in_features=13, out_features=12, bias=True)
)
_num: 4 Sequential(
  (l1): Linear(in_features=1, out_features=13, bias=True)
  (l2): Linear(in_features=13, out_features=12, bias=True)
)
Sequential(
  (l1): Linear(in_features=1, out_features=13, bias=True)
  (l2): Linear(in_features=13, out_features=12, bias=True)
)


In [3]:
grad_list = []
x = torch.randn(2,1)
y = torch.tensor([[13, 2],[3, 4]])
z = torch.tensor(np.asarray([[1, 2],[3, 4]]))#tensor构造函数比较强大，可以通过不同的ararry-like类型进行构造tensor
print(x, x.type())
print(y, y.type())#可以看到tensor能够自动匹配合适的数字类型
print(z, z.type())

tensor([[ 0.5468],
        [-0.4557]]) torch.FloatTensor
tensor([[ 13,   2],
        [  3,   4]]) torch.LongTensor
tensor([[ 1,  2],
        [ 3,  4]]) torch.LongTensor


In [17]:
print(z.requires_grad)#默认不需要梯度

False


In [25]:
x.requires_grad = True
y = torch.ones(2,2, requires_grad=True)
x = y+x
x.backward()

RuntimeError: you can only change requires_grad flags of leaf variables.

In [24]:
l = [1,2,3,4]
print(l[start]);start =1

NameError: name 'start' is not defined

In [5]:
w1 = torch.tensor([2.], requires_grad=True)
w2 = torch.tensor([2.], requires_grad=True)
x2 = torch.rand(1)
y2 = x2**w1
z2 = w2*y2+1
z2.backward()
print(x2.grad)
print(y2.grad)
print(w1.grad)
print(w2.grad)

None
None
tensor([-0.3122])
tensor([ 0.5880])
