In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F

`torch.sort(input, dim=None)`<br>
返回排序的数组和索引和排序号的数组**选择行就是列操作**,排序好的数组根据索引就知道相应的数值大小了,索引array是为了方便对应源array中数据的位置<br>
默认维度为最后一个维度,即对里面的最小单元进行排序.

`NMS`

In [ ]:
def nms(boxes, nms_thresh):
    if len(boxes) ==0 :
        return boxes
    det_confs = torch.zeros(len(boxes))
    for i in range(len(boxes)):
        det_confs[i] = 1 - boxes[i][4]
    _, sortIds = torch.sort(det_confs)
    outboxes = []
    for i in range()

In [13]:
under[:,[1,2,3]]#使用[]选择多个单独列

tensor([[ 4,  3,  7],
        [ 1,  6,  8]])

`torch.linspace(start, end, steps)`在[start, end]范围内取step个点<br>
`torch.repeat(*sizes)`沿着指定维度重复<br>

In [34]:
x = torch.tensor([1,2,3])#输入在
x.repeat(4,4,4)#*size每个位置的数字相是在指定的轴的重复次数

tensor([[[ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3]],

        [[ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3]],

        [[ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3]],

        [[ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
         [ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3]]])

`torch.Tensor.index_select()`按照指定维度和轴进行索引数据

In [28]:
torch.linspace(0, 10, 10).repeat(10,1).shape

torch.Size([10, 10])

In [6]:
under = torch.tensor([[1,4,3,7,9],[5,1,6,8,3]])
torch.sort(under)#dim=0
#不会更改源数组

(tensor([[ 1,  3,  4,  7,  9],
         [ 1,  3,  5,  6,  8]]), tensor([[ 0,  2,  1,  3,  4],
         [ 1,  4,  0,  2,  3]]))

如果tensor的shape=(A,B,C),排序制定了dim=n,那么排序号的索引范围就是$(0-len(dim_n))$

In [11]:
sort, index = torch.sort(under, dim=0)
print(sort)
print(index)#索引也成了dim指定维度上的索引注意与上面dim=1进行对比,都是在第

tensor([[ 1,  1,  3,  7,  3],
        [ 5,  4,  6,  8,  9]])
tensor([[ 0,  1,  0,  0,  1],
        [ 1,  0,  1,  1,  0]])


In [9]:
input = torch.arange(1, 5, requires_grad=True).view(1, 1, 2, 2) 
m = nn.Upsample(scale_factor=2) #上采样
avg = nn.AdaptiveAvgPool2d(1)
x = m(input)
avg(x)
x.squeeze().backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [11]:
layer_regex = {
    # all layers but the backbone
    "heads": r"(fpn.P5\_.*)|(fpn.P4\_.*)|(fpn.P3\_.*)|(fpn.P2\_.*)|(rpn.*)|(classifier.*)|(mask.*)",
    # From a specific Resnet stage and up
    "3+": r"(fpn.C3.*)|(fpn.C4.*)|(fpn.C5.*)|(fpn.P5\_.*)|(fpn.P4\_.*)|(fpn.P3\_.*)|(fpn.P2\_.*)|(rpn.*)|(classifier.*)|(mask.*)",
    "4+": r"(fpn.C4.*)|(fpn.C5.*)|(fpn.P5\_.*)|(fpn.P4\_.*)|(fpn.P3\_.*)|(fpn.P2\_.*)|(rpn.*)|(classifier.*)|(mask.*)",
    "5+": r"(fpn.C5.*)|(fpn.P5\_.*)|(fpn.P4\_.*)|(fpn.P3\_.*)|(fpn.P2\_.*)|(rpn.*)|(classifier.*)|(mask.*)",
    # All layers
    "all": ".*",
}
layers = '4+'
if layers in layer_regex.keys():
    layers = layer_regex[layers]
# layer_regex[layers]
for i in layer_regex.values():
    print(i)

(fpn.P5\_.*)|(fpn.P4\_.*)|(fpn.P3\_.*)|(fpn.P2\_.*)|(rpn.*)|(classifier.*)|(mask.*)
(fpn.C3.*)|(fpn.C4.*)|(fpn.C5.*)|(fpn.P5\_.*)|(fpn.P4\_.*)|(fpn.P3\_.*)|(fpn.P2\_.*)|(rpn.*)|(classifier.*)|(mask.*)
(fpn.C4.*)|(fpn.C5.*)|(fpn.P5\_.*)|(fpn.P4\_.*)|(fpn.P3\_.*)|(fpn.P2\_.*)|(rpn.*)|(classifier.*)|(mask.*)
(fpn.C5.*)|(fpn.P5\_.*)|(fpn.P4\_.*)|(fpn.P3\_.*)|(fpn.P2\_.*)|(rpn.*)|(classifier.*)|(mask.*)
.*


`torch`的数据bool型广播,Tensor不像numpy,全是数字,没有bool类型的值

In [10]:
a = torch.tensor([1,-2,3,4,-1])
a>0#广播后自动转换为uint8

tensor([ 1,  0,  1,  1,  0], dtype=torch.uint8)

In [12]:
a > torch.tensor([1,0,0,1,1])#也可以使用另一个tensor进行bool判断

tensor([ 0,  0,  1,  1,  0], dtype=torch.uint8)

In [3]:
a.int()

tensor([ 1, -2,  3,  4, -1], dtype=torch.int32)

In [ ]:
torch.nn.BCELoss()

In [46]:
torch.repeat()

TypeError: repeat() missing 1 required positional arguments: "repeats"

In [5]:
a = torch.tensor([[[1,2,3], [3,4,5]],[[1,5,6],[7,1,8]], [[1,5,6],[1,2,119]]])
b = torch.tensor([[2,3,4],[3,1,3]])
c = torch.tensor([[4,3,1],[3,2,6]])
torch.max(a, 0)#tensor也可以比较大小,取对应位置较大者,max返回一个元组(数值,最大值索引)

(tensor([[   1,    5,    6],
         [   7,    4,  119]]), tensor([[ 0,  1,  1],
         [ 1,  0,  2]]))

> max, sum, mean,min这些函数,指定在哪个维度上,哪个维度上便会消失,变为1,返回的索引坐标是在指定的维度上的,

In [7]:
t = torch.tensor([[1,2,3],[8,5,6]])
torch.max(t, 1)#指定了第一个维度,可以看到返回的坐标就是在原来数据dim=1维度上的索引

(tensor([ 3,  8]), tensor([ 2,  0]))

`torch.tolist()`将所有tensor内容转换为list,tensor也有这个方法

In [8]:
t.tolist()

[[1, 2, 3], [8, 5, 6]]

`torch.nonzero(input)`<br>
返回的是非零元素的位置索引,长度就是input中非零元素的个数

`torch`

`torch.cat()`在已存在的dim上合并seq,
`torch.chunk(tensor, chunks, dim=0)`在指定维度上,将tensor分成chunks块

In [5]:
a = [torch.randn(2,3) for i in range(10)]
torch.cat(a, dim=0).shape


torch.Size([20, 3])

In [59]:
torch.chunk(a,dim=0,chunks=3)#将一个tensor分成几块

(tensor([[[ 1,  2,  3],
          [ 3,  4,  5]]]), tensor([[[ 1,  5,  6],
          [ 7,  1,  8]]]), tensor([[[   1,    5,    6],
          [   1,    2,  119]]]))

In [39]:
print(b<c)
torch.nonzero(b<c)#返回一个tensor包含非零元素位置的坐标(索引),返回一个seq[(first_loc), (second_loc)....]每个位置根据input的数据的

tensor([[ 1,  0,  0],
        [ 0,  1,  1]], dtype=torch.uint8)


tensor([[ 0,  0],
        [ 1,  1],
        [ 1,  2]])

In [7]:
class Test():
    def __init__(self):
        self.var1 = 100
        self.var2 = 200
a = Test()
a.__dict__['var1']

100

`torch.where()`
$$    out_i = \begin{cases}
        x_i & \text{if } condition_i \\
        y_i & \text{otherwise} \\
    \end{cases}$$

In [20]:
torch.max(torch.tensor([1,2,3,4]))#如果不指定维度,返回的是tensor中最大的数字

tensor(4)

In [5]:
a = torch.tensor([[1,2],[3,4],[5,6]])
a.permute(1,0)#相当于转置,改变了内部数据的排布方式

tensor([[ 1,  3,  5],
        [ 2,  4,  6]])

In [56]:
torch.tensor([[1,1,1],[2,2,2]]).repeat(2,3)

tensor([[ 1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2]])

In [47]:
target = torch.tensor([1,0,1,0]).float()
pred = F.sigmoid(torch.tensor([3.0,4,2,1]))
loss = F.binary_cross_entropy(pred, target)
loss

tensor(1.3767)

`transpose`和`permute`的用法

In [8]:
a.transpose(1,0)#效果和permute是一致的

tensor([[ 1,  3,  5],
        [ 2,  4,  6]])

In [ ]:
a.reshape(2,3)#reshape不改变数据的排布方式,只是改变了切分,相当于把数据拉成一条直线,根据指定的形状切开

>注意:reshape和view指定的参数是shape,permute和transpose指定的是axis轴的位置,相当于把轴对换<br>
tranpose就是一个位置索引的变换,就是想把某个轴的位置放在自己需要的地方,取得时候还是要按之前的含义取,但是其在内存中的顺序会发生改变,再使用reshpae切分的时候可能就不是之前的含义了<br>
**只用reshape不改变内存位置,还可以再reshape回去**<br>
**只使用transpose可以再transpose到原来的位置**<br>
两种方式交叉使用可能就不太妙了<br>

In [7]:
a.view(2,3)#效果和reshape差不多

tensor([[ 1,  2,  3],
        [ 4,  5,  6]])

In [9]:
a.view(2,-1)#-1表示自动求剩下的那个轴应该有的形状

tensor([[ 1,  2,  3],
        [ 4,  5,  6]])

`torch.max(input)`返回所有元素的最大值
`torch.max(input, dim)`返回指定维度上的最大值和对应index,注意这个坐标是在dim维度上的index

In [66]:
print(a)

tensor([[[   1,    2,    3],
         [   3,    4,    5]],

        [[   1,    5,    6],
         [   7,    1,    8]],

        [[   1,    5,    6],
         [   1,    2,  119]]])


In [67]:
torch.max(a, dim=2)

(tensor([[   3,    5],
         [   6,    8],
         [   6,  119]]), tensor([[ 2,  2],
         [ 2,  2],
         [ 2,  2]]))

In [ ]:
torch.squeeze()#返回一个去除维度为1所在的维度

In [12]:
torch.Tensor.contiguous()#返回一个连续存储位置的tensor

TypeError: descriptor 'contiguous' of 'torch._C._TensorBase' object needs an argument

**NLLoss为什么一定要搭配log_softmax??如果接softmax求得loss为负值**

`torch.cat()`多个tensor拼接,不提升维度<br>
两个tensor的组合,只会在原有shape上叠加,**不会提升维度**.a=(A,B)只会在某一个axis上做组合,注意多个tensor至少在有一个axis上有一致的shape<br>
(2,2) 和(3,2)可以在axis=0拼接,因为axis=1相同,axis=0上面的不同
>axis是合并方向轴,通过合并后新的shape可以看到a=(A,B) b=(C,B) 合并后 (A+C,B),在哪个轴合并,哪个轴上的新维度就是原来的相加


In [123]:
a = torch.tensor([])
if not a.size():
    print('T')
tya.size()

`torch.randperm(n)`返回一个0到n-1的随机数字排列

In [78]:
torch.randperm(10)

tensor([ 8,  2,  5,  7,  9,  3,  6,  0,  1,  4])

In [23]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8],[9,10]])
torch.cat([a,b], 0)

tensor([[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8],
        [  9,  10]])

In [22]:
a = torch.tensor([[1,2,3],[3,4,3]])
b = torch.tensor([[5,6],[7,8]])
torch.cat([a,b], 1)#必须在一个维度上有相同的

tensor([[ 1,  2,  3,  5,  6],
        [ 3,  4,  3,  7,  8]])

`nn.logsoftmax(dim=0)`

In [21]:
a = torch.tensor([[1,1],[2,2]],dtype=torch.float32)

In [24]:
F.log_softmax(a, dim=0)

tensor([[-1.3133, -1.3133],
        [-0.3133, -0.3133]])

In [16]:
for i in lsm.parameters():
    print(i)

In [17]:
weight = torch.arange(27).reshape(3,3,3)
bias = torch.zeros(3,3,3).float()

In [18]:
torch.batch_norm(weight, bias, 0, 1)

TypeError: batch_norm(): argument 'bias' (position 3) must be Tensor, not int