# sklearn数据集划分
`sk`

In [53]:
import torch
a = torch.tensor([1,2,3,4])
b = torch.tensor([3])
c = a * b
c 
arr1 = torch.tensor([[1,2],[1,2], [1,2]])
arr2 = torch.tensor([[1,1],[1,3]])
bias = torch.tensor([1,1])
# arr = torch.mul(arr1,arr2)
arr = torch.addmm(arr1, arr2)
arr

TypeError: addmm() received an invalid combination of arguments - got (Tensor, Tensor), but expected (Tensor input, Tensor mat1, Tensor mat2, float beta, float alpha, Tensor out)

In [ ]:
torch.tensor([1,2])#生成的是一个2的数组,不是矩阵维度是(2),不是(1x2),因此无法在矩阵中进行运算
#如果想使用,必须增加一个维度,可以用reshape或者

In [82]:
w = torch.tensor([1,2]).reshape(1, 2)
x = torch.tensor([[1,2],[1,2]])
torch.mm(w,x)#

tensor([[ 3,  6]])

In [16]:
torch.tensor([[1,2], [1,2],[1,2]]).unsqueeze(1)

tensor([[[ 1,  2]],

        [[ 1,  2]],

        [[ 1,  2]]])

In [1]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import torch
X = pd.read_csv('label.csv')
# X.loc[10, 'img_path']
skf = StratifiedKFold(n_splits=2)
# torch.arange()
for train_index, test_index in skf.split(X['img_path'], X['label']):
#     print('train', train_index.shape, 'test',test_index.shape)
    print(X.loc[train_index])#返回的index是索引值 

                                               img_path  label
509   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
510   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
511   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
512   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
513   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
514   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
515   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
516   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
517   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
518   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
519   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
520   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
521   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
522   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...      0
523   /home/bobo/WDD/Tianchi/data/guangdong_round1_t...

`train_test_split(train_seq, label_seq, test_size=ratio(test/train))`
**return:**返回的是train_imgs, val_imgs, train_label, val_label四个集合

In [29]:
train_imgs, val_imgs, train_label, val_label =\
    train_test_split(X['img_path'], X['label'], test_size=0.1)
print(train_imgs.shape, val_imgs.shape, val_imgs.shape, val_label.shape)
print(train_label)

(1796,) (200,) (200,) (200,)
328      0
675      0
386      0
1090     3
1576    10
653      0
815      0
1257     5
1392     1
560      0
1495     6
1577    10
189      0
759      0
617      0
1699    10
120      0
4        0
64       0
380      0
1675    10
804      0
1580    10
1714    10
1669    10
333      0
486      0
633      0
1043     8
1781     2
        ..
1057     8
726      0
1265     5
1825     2
6        0
1432     6
185      0
1437     6
980      0
20       0
171      0
1433     6
1857     7
1751     2
930      0
247      0
232      0
623      0
438      0
1900     7
1189     5
261      0
565      0
1984     4
57       0
1841     2
899      0
1064     3
457      0
296      0
Name: label, Length: 1796, dtype: int64


**备注:**

train_test_split是按照最外层维度进行划分的,也就是意味着[A,B,C,D,E]->[A,B,C,D] and [E],如果传入的是DataFrame,也就意味着会对每一行的信息划分,如果不需要返回index,需要在传值的时候进行切片索引,对于传入的series和list等,都是同样的道理


`sklearn.model_selection.KFold(n_splits=3, shuffle=False, random_state=None)`<br>
**思路：**将训练/测试数据集划分n_splits个互斥子集，每次用其中一个子集当作验证集，剩下的n_splits-1个作为训练集，进行n_splits次训练和测试，得到n_splits个结果<br>
**注意点：**对于不能均等份的数据集，其前n_samples % n_splits子集拥有n_samples // n_splits + 1个样本，其余子集都只有n_samples // n_splits样本<br>

In [9]:
from sklearn.model_selection import KFold
import numpy as np
X = np.arange(24).reshape(12,2)
# print(X)
y = np.random.choice([1,2],12,p=[0.4,0.6])
kf = KFold(n_splits=5,shuffle=False)
for train_index , test_index in kf.split(X):
    print('train:', X[train_index], 'test', X[test_index])#返回的是index
#     print('train_index:%s , test_index: %s ' %(train_index,test_index))

train: [[ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] test [[0 1]
 [2 3]
 [4 5]]
train: [[ 0  1]
 [ 2  3]
 [ 4  5]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] test [[ 6  7]
 [ 8  9]
 [10 11]]
train: [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] test [[12 13]
 [14 15]]
train: [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [20 21]
 [22 23]] test [[16 17]
 [18 19]]
train: [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] test [[20 21]
 [22 23]]


In [11]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
y=np.array([1,1,1,2,2,2])
skf=StratifiedKFold(n_splits=3)
skf.get_n_splits(X,y)
print(skf)
for train_index,test_index in skf.split(X,y):
    print("Train Index:",train_index,",Test Index:",test_index)
    X_train,X_test=X[train_index],X[test_index]
    print(X_train)
    y_train,y_test=y[train_index],y[test_index]

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)
Train Index: [1 2 4 5] ,Test Index: [0 3]
[[ 3  4]
 [ 5  6]
 [ 9 10]
 [11 12]]
Train Index: [0 2 3 5] ,Test Index: [1 4]
[[ 1  2]
 [ 5  6]
 [ 7  8]
 [11 12]]
Train Index: [0 1 3 4] ,Test Index: [2 5]
[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]]
